#!/usr/bin/env php
<?php

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
defined('MODULE_NAME') or define('MODULE_NAME', 'console');
defined('BASE_PATH') or define('BASE_PATH', __DIR__ . '/app/modules/Console');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/app/config/bootstrap.php';

$config = \App\App::i()->getConfig();

$application = new yii\console\Application($config);
$exitCode    = $application->run();
exit($exitCode);
